# Generated by Django 2.2.1 on 2019-07-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Picture',
        ),
    ]
