# Generated by Django 2.2.1 on 2019-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20190705_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='https://www.eltis.org/sites/default/files/styles/web_quality/public/default_images/photo_default_2.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo_path',
            field=models.CharField(default='https://summer.pes.edu/wp-content/uploads/2019/02/default-2.jpg', max_length=255),
        ),
    ]
