# Generated by Django 2.2.1 on 2019-08-09 19:20

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20190707_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=geoposition.fields.GeopositionField(default=(15.2, 152.2), max_length=42),
            preserve_default=False,
        ),
    ]
