# Generated by Django 2.2.1 on 2019-08-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20190809_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='position',
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.CharField(default=15.32, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.CharField(default=(15.2, 157.2), max_length=255),
            preserve_default=False,
        ),
    ]
