# Generated by Django 2.2.1 on 2019-05-24 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20190524_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Anomaly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaly',
            name='description',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='consulted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='consulted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly', to='Post.Post'),
            preserve_default=False,
        ),
    ]
