# Generated by Django 2.2.1 on 2019-08-08 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Anomaly', '0002_auto_20190524_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalySignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signaledAnomaly', to='Anomaly.Anomaly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signaledBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
