<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-05-18 18:11
=======
# Generated by Django 2.2 on 2019-05-02 14:48
>>>>>>> 0d8bc60f35c4be83b6a3c894ad1d1673e79c6aef

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citys', to='Address.State')),
=======
                ('zip_code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Address.State')),
>>>>>>> 0d8bc60f35c4be83b6a3c894ad1d1673e79c6aef
            ],
        ),
    ]
